### ISSUE TITLE
Fix Contact list

### ISSUE THREAD

**Issue by ggrassi09** [academicweapon7/COP4331-Group-17#7]
![image](https://github.com/academicweapon7/COP4331-Group-17/assets/131699222/959a7263-7b0e-4de1-89a0-6f2c9aad54f1)

Currently contacts are not displayed until after a search is conducted, to my understanding this should be populated automatically when the page is loaded.

Contact list is not displaying yachtSize or phoneNumber.

Small black text is a bit difficult to read with the current background.

**Comment by alyssabuckingham** [comment]
everything except the text has been fixed
