### ISSUE TITLE
Fix "Logged In as ______" message 

### ISSUE THREAD

**Issue by ggrassi09** [academicweapon7/COP4331-Group-17#8]
![image](https://github.com/academicweapon7/COP4331-Group-17/assets/131699222/6134440d-16c9-46b2-b5c3-495364a6d1ed)

Text for the user currently logged in is a bit hard to read with the small black text.

Also the message does not appear until after a search is conducted.

**Comment by alyssabuckingham** [comment]
appears now when page laods
